name: checks

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          python-version: "3.12"
      - name: Install from lockfile
        run: uv sync --frozen --all-groups
      - name: Ruff
        run: uv run ruff check .
      - name: Mypy
        run: uv run mypy
      - name: Pytest
        run: uv run pytest
